[Mistral-7B-Instruct-v0.3]
hf = bartowski/Mistral-7B-Instruct-v0.3-GGUF:Q4_K_M
tags = chat

; K2-Horizon is currently unsupported by llama.cpp

; [K2-Horizon-3.7B]
; hf = IFM/K2-Horizon-3.7B-GGUF:Q4_K_M
; tags = chat

; [K2-Horizon-7B]
; hf = IFM/K2-Horizon-7B-GGUF:Q4_K_M
; tags = chat

; [K2-Horizon-MoVA-36B-A4B]
; hf = IFM/K2-Horizon-MoVA-36B-A4B-GGUF:Q4_K_M
; tags = chat

[MiniCPM5-2B]
hf = openbmb/MiniCPM5-2B-GGUF:Q4_K_M
tags = chat, default

[Granite-4.2-3B]
hf = ibm-granite/granite-4.2-3b-GGUF:Q4_K_M
tags = chat

[Qwen3.5-4B]
hf = unsloth/Qwen3.5-4B-GGUF:Q4_K_M
tags = chat

[Nemotron-3-Nano-4B]
hf = nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF:Q4_K_M
tags = chat

[Ling-3.0-tiny]
hf = inclusionAI/Ling-3.0-tiny-GGUF:Q4_K_M
tags = chat

[Gemma-4-12B]
hf = unsloth/gemma-4-12b-it-GGUF:Q4_K_M
tags = chat

[Qwen3.5-9B]
hf = unsloth/Qwen3.5-9B-GGUF:Q4_K_M
tags = chat

[Nemotron-3-Nano-9B-v2]
hf = bartowski/nvidia_NVIDIA-Nemotron-Nano-9B-v2-GGUF:Q4_K_M
tags = chat

[Granite-4.2-8B]
hf = ibm-granite/granite-4.2-8b-GGUF:Q4_K_M
tags = chat

[Apriel-1.6-15B-Thinker]
hf = bartowski/ServiceNow-AI_Apriel-1.6-15b-Thinker-GGUF:Q4_K_M
tags = chat

[gpt-oss-20B]
hf = unsloth/gpt-oss-20b-GGUF:Q4_K_M
tags = chat

[Qwen3.8-27B]
hf = unsloth/Qwen3.8-27B-GGUF:Q4_K_M
tags = chat

[Qwen3.6-27B]
hf = unsloth/Qwen3.6-27B-GGUF:Q4_K_M
tags = chat

[Gemma-4-31B]
hf = unsloth/gemma-4-31B-it-GGUF:Q4_K_M
tags = chat

[Gemma-4-26B-A4B]
hf = unsloth/gemma-4-26B-A4B-it-GGUF:Q4_K_M
tags = chat

[Nemotron-3.5-Lightning-30B-A3B]
hf = bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF:Q4_K_M
tags = chat

[Devstral-Small-2505]
hf = mistralai/Devstral-Small-2505_gguf:Q4_K_M
tags = chat

[Muse-Glimmer-30B]
hf = meta-models/Muse-Glimmer-30B-GGUF:Q4_K_M
tags = chat

[Ling-3.0-Flash]
hf = bartowski/Ling-3.0-flash-GGUF:Q4_K_M
tags = chat

[Ling-3.0-Flash-Fin]
hf = bartowski/Ling-3.0-flash-Fin-GGUF:Q4_K_M
tags = chat

[Qwen3.5-122B-A10B]
hf = unsloth/Qwen3.5-122B-A10B-GGUF:Q4_K_M
tags = chat

[Mistral-Small-4-119B-2603]
hf = bartowski/mistralai_Mistral-Small-4-119B-2603-GGUF:Q4_K_M
tags = chat

; embeddings

[all-MiniLM-L6-v2]
hf = infosecinnovations/all-MiniLM-L6-v2-GGUF:Q8_0
tags = embeddings

[bge-m3]
hf = ggml-org/bge-m3-Q8_0-GGUF:Q8_0
tags = embeddings

[nomic-embed-text-v2-moe]
hf = nomic-ai/nomic-embed-text-v2-moe-GGUF:Q8_0
tags = embeddings
shabti_query_prefix = "search_query: "
shabti_document_prefix = "search_document: "

[embeddinggemma-300M]
hf = ggml-org/embeddinggemma-300M-GGUF:Q8_0
tags = embeddings
shabti_query_prefix = "task: search result | query: "
shabti_document_prefix = "title: none | text: "

[snowflake-arctic-embed-s]
hf = infosecinnovations/snowflake-arctic-embed-s-GGUF:Q8_0
tags = embeddings
shabti_query_prefix = "Represent this sentence for searching relevant passages: "

[snowflake-arctic-embed-l-v2.0]
hf = infosecinnovations/snowflake-arctic-embed-l-v2.0-GGUF:Q8_0
tags = embeddings
shabti_query_prefix = "query: "
